---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ .Values.name }}
spec:
  prefix: /{{ .Values.prefix }}/
  service: {{ .Values.name }}
  docs:
    path: "/docs"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8090
  selector:
    app: {{ .Values.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: backend
        image: docker.io/alixcook11/openapi-tester:0.0.3
        ports:
        - name: http
          containerPort: 8090
        resources:
          limits:
            cpu: "0.1"
            memory: 50Mi
